apibara/starknet-react

.changeset/silent-planes-hammer.md
packages/core/src/providers/starknet/manager.ts
packages/core/test/providers/starknet.test.tsx
website/src/components/Demo.tsx

fix: detect if starknet plugin is installed

---

website/docs/intro.md

Closes #45 .
Fixed Getting Started section docs.

(docs): getting started section

---

.changeset/slimy-falcons-tap.md
packages/core/src/connectors/base.ts
packages/core/src/connectors/injected.ts
packages/core/src/providers/index.tsx
packages/core/src/providers/starknet/manager.ts
packages/core/src/providers/starknet/model.ts
packages/core/src/providers/starknet/provider.tsx
website/docs/intro.md
website/package.json
website/src/components/Demo.tsx
yarn.lock

minor modification to the interface to support preauth checks

feat(connectors): update to support preauth

---

.changeset/strong-dolls-count.md
examples/starknet-react-next/src/pages/_app.tsx
packages/core/src/connectors/injected.ts
yarn.lock

This the fix discussed in #69. It's more of a temporary fix while we work on better Argent/Injected detection.

fix(connectors): improve starknet detection on autoconnect

---

.changeset/strong-pets-jump.md
packages/core/src/hooks/execute.ts
pnpm-lock.yaml

Only check installed wallets for multicall

---

package.json
packages/core/src/hooks/block.ts
packages/core/src/hooks/call.ts
packages/core/src/hooks/contract.test.tsx
packages/core/src/hooks/contract.ts
packages/core/src/hooks/deploy.test.tsx
packages/core/src/hooks/network.test.tsx
packages/core/src/hooks/sign.test.tsx
packages/core/src/hooks/sign.ts
packages/core/src/network.ts
packages/core/test/devnet.ts
pnpm-lock.yaml
website/components/CodeBlock/scope.ts

Fixes various breaking changes with the newest version of starknet@next

feat: update for starknet 4.14

---

packages/core/src/providers/starknet.tsx

Set provider back to default provider on disconnect

feat: set default provider on disconnect

---

packages/core/src/connectors/base.ts
packages/core/src/connectors/injected.ts
packages/core/src/hooks/account.test.tsx
packages/core/src/providers/starknet.tsx
packages/core/test/devnet.ts

Handle account and network changes events

Handle account and network changes

---

.changeset/bright-gifts-chew.md
.changeset/lovely-cars-hope.md
packages/core/src/hooks/connectors.test.tsx
packages/core/src/hooks/connectors.ts

#201 
- create isLoading boolean : initialize to true, on refresh when available is populated by connectors set isLoading to false
- update corresponding tests

feat: useConnector should return isLoading

---

website/pages/get-started.tsx

docs: updated get started page to suggest `create-starknet`

---

.github/PULL_REQUEST_TEMPLATE/project.md
LICENSE
README.md
packages/core/README.md
packages/core/src/hooks/deploy.ts
packages/core/src/hooks/execute.ts
packages/core/src/hooks/sign.test.tsx
packages/core/src/hooks/sign.ts
packages/core/src/network.ts
packages/core/src/providers/starknet.tsx
website/README.md
website/components/Header.tsx
website/pages/get-started.tsx
website/pages/hooks/[name].tsx
website/pages/hooks/index.tsx
website/pages/index.tsx

Change StarkNet to Starknet #240

docs: Update README.md

---

website/app/hooks/[name]/page.tsx

Next 13 requires to export dynamic paths to statically export the website

fix: export dynamic paths in website

---

.changeset/mean-goats-tie.md
.changeset/orange-doors-tie.md
packages/core/package.json
packages/core/src/providers/starknet.tsx
pnpm-lock.yaml
website/components/CodeBlock/live.tsx

chore: update dependencies

---

package.json
packages/core/package.json
pnpm-lock.yaml
website/components/DeprecationNotice.tsx
website/components/Hook.tsx
website/components/HookSummary.tsx
website/components/Hooks.tsx
website/components/Tab.tsx
website/lib/typedoc.ts
website/package.json

- Upgraded typedoc version to 0.24.8
- Refactor clients components that use typedoc functions to server components
- Move some of client components to the leaf of components tree.

feat: upgrade typedoc version and refactor client components

---

packages/chains/README.md
packages/chains/package.json
packages/chains/src/index.ts
packages/chains/src/starknet.ts
packages/chains/src/types.ts
packages/chains/tsconfig.json
packages/core/src/hooks/call.test.tsx
packages/core/src/hooks/starknetid.ts
pnpm-lock.yaml

**Summary**
Chain definitions contain all the information required for starknet react to interact with the chain.
This is the first step towards using a public json-rpc provider for all interactions with Starknet.

chains: add starknet chains

---

website/content/hooks/mutation/useContractWrite.mdx
website/content/hooks/mutation/useSignTypedData.mdx
website/content/hooks/query/useStarkName.mdx

- Updated the documentation for 3 hooks
- useContractWrite
- useSignTypedData
- useStarkName

doc: update 3 hooks

---

packages/core/src/hooks/useContract.ts
website/content/hooks/useContract.mdx

Add custom providers for useContract, and the docs that go with it !

Use contract provider

---

packages/core/src/hooks/useAccount.test.ts
packages/core/src/hooks/useAccount.ts

Add chainId to useAccount return

---

.changeset/eleven-snails-grow.md
packages/core/src/providers/lava.ts

Wrong typo, i've corrected the function name

fix: lava provider typo

---

.changeset/smooth-dolphins-swim.md
README.md
packages/chains/src/index.ts
packages/chains/src/starknet.ts
website/app/layout.tsx
website/components/notice.tsx
website/content/docs/getting-started.mdx
website/content/hooks/useInjectedConnectors.mdx

Starknet is switching to testnet. Prepare starknet react for that.

chains: add sepolia testnet

---

.changeset/selfish-rules-remember.md
packages/core/package.json
website/components/demos/send-transaction.tsx

core: fix package.json types/main order
website: fix send transaction demo

core: fix package.json types/main order

---

.changeset/forty-deers-brush.md
packages/core/src/hooks/useStarkAddress.ts
packages/core/src/hooks/useStarkName.ts
packages/core/src/hooks/useStarkProfile.ts

This PR updates the starknet ID Sepolia contract addresses.

fix: update starknetid sepolia contracts

---

packages/core/src/hooks/useBlock.test.ts
packages/core/src/hooks/useBlockNumber.test.ts

- Fixes tests for `useBlock` and `useBlockNumber` hook

fix: useBlock and useBlockNumber tests

---

.github/workflows/build.yml
docs/components/demo/connect-wallet.tsx
docs/package.json
packages/chains/src/devnet.ts
packages/chains/src/index.ts
packages/chains/src/starknet.ts
packages/core/package.json
packages/core/src/connectors/base.ts
packages/core/src/connectors/injected.ts
packages/core/src/connectors/mock.ts
packages/core/src/context/starknet.test.tsx
packages/core/src/context/starknet.tsx
packages/core/src/explorers/viewblock.ts
packages/core/src/hooks/index.ts
packages/core/src/hooks/useAccount.test.ts
packages/core/src/hooks/useAccount.ts
packages/core/src/hooks/useBalance.test.ts
packages/core/src/hooks/useCall.test.ts
packages/core/src/hooks/useConnect.test.ts
packages/core/src/hooks/useContract.test.ts
packages/core/src/hooks/useContractWrite.test.ts
packages/core/src/hooks/useReadContract.test.ts
packages/core/src/hooks/useStarkAddress.ts
packages/core/src/hooks/useStarkProfile.ts
packages/core/src/hooks/useWalletRequest.ts
packages/core/src/providers/public.test.ts
packages/core/test/devnet.ts
pnpm-lock.yaml

- updated `Connector` , `InjectedConnector` & `MockConnector`
- updated `starknet.js` to `v6.9.0`
- added `useWalletRequest` hook
- removed `goerli` & updated `devnet` `chainId` in `@starknet-react/chains`
- updated `devnet` image to `v0.0.6` in CI
- fixed test cases

feat: update connector and mock connector 

---

.github/workflows/build.yml
docs/components/demo/stark-name.tsx
docs/components/demo/stark-profile.tsx
packages/core/src/connectors/injected.ts
packages/core/src/hooks/useStarkName.ts
packages/core/src/hooks/useStarkProfile.ts
turbo.json

This PR fixes the useStarkProfile hook & updates the demo addresses.

fix: useStarkProfile

---

docs/components/demo/starknetkit.tsx
docs/components/starknetkit/index.ts
docs/components/starknetkit/starknetkit-connectors.ts
docs/package.json
docs/pages/demo/starknetkit.mdx
docs/tsconfig.json
packages/core/src/hooks/use-account.ts
pnpm-lock.yaml

this updates the starknetkit demo to experiment with web and mobile based wallets

docs: update starknetkit demo for experiment

---

.changeset/purple-buttons-sniff.md

Make a release for @starknet-react/core

core: prepare release

---

docs/pages/docs/hooks/use-deploy-account.mdx

Credit to @TeddyNotBear for reporting this.

docs: fix useDeployAccount page title

---

change/@starknet-react-core-2cb32fda-224a-4b36-86e2-acffaa17d520.json
docs/components/demo/change-default-network.tsx
docs/components/demo/index.ts
docs/components/starknet/index.tsx
docs/components/starknet/provider.tsx
docs/pages/demo/change-default-network.mdx
docs/pages/demo/index.mdx
docs/pages/docs/starknet-config.mdx
docs/sidebar.ts
packages/core/src/context/starknet.tsx

Adds a `defaultChain` arg to `StarknetConfig` that allows changing the default chain used when no wallet is connected

feat: default chain

---

change/@starknet-react-chains-c3a197f9-d51a-4721-a7a5-48d5b3b49996.json
change/@starknet-react-core-d1db7935-6e23-49ae-87e5-d02a85f3a8d9.json
change/@starknet-react-kakarot-1bd26f08-4276-4276-b8a6-4c4dafe07a32.json
packages/chains/package.json
packages/core/package.json
packages/kakarot/package.json

Sync the package version with npm to unblock ci

sync package version

---

docs/pages/docs/kakarot-connectors.mdx
docs/sidebar.ts

- adding a short explanation and a code snippet to get things started
next steps:
- flow diagram?

docs: add kakarot v1 docs (very light)

---

biome.json
change/@starknet-react-core-f9ff5aa3-9d70-45ff-ac58-ac74c4af7c0b.json
change/@starknet-react-typescript-config-119bfdf5-b9c7-4b1b-8a3c-02da133d9507.json
change/create-starknet-a1fe6272-3c78-44aa-aa74-c8715bf6bdaa.json
docs/components/demo/declare-contract.tsx
docs/components/demo/deploy-contract.tsx
docs/components/demo/index.ts
docs/components/demo/stark-address.tsx
docs/components/demo/starknetkit.tsx
docs/components/demo/switch-chain.tsx
docs/lib/erc20_class_abi.ts
docs/package.json
docs/pages/demo/deploy-contract.mdx
docs/pages/demo/index.mdx
docs/pages/docs/deploying-contracts.mdx
docs/pages/docs/hooks/use-universal-deployer-contract.mdx
docs/sidebar.ts
docs/tsconfig.json
packages/core/src/context/index.tsx
packages/core/src/hooks/index.ts
packages/core/src/hooks/use-account.ts
packages/core/src/hooks/use-stark-name.ts
packages/core/src/hooks/use-universal-deployer-contract.tsx
packages/create-starknet/src/templates/vite/src/App.tsx
packages/create-starknet/src/templates/vite/src/components/Header.tsx
packages/create-starknet/src/templates/vite/src/components/starknet/ConnectModal.tsx
packages/typescript-config/base.json
packages/typescript-config/react-library.json
pnpm-lock.yaml

core: add useUniversalDeployerContract hook

---

change/@starknet-react-core-7ad8aa4e-d8ed-46e8-9231-bd5a5313e78a.json
packages/core/src/context/starknet.test.tsx
packages/core/src/context/starknet.tsx

Fix: duplicated chain ids

---

docs/package.json
docs/pages/docs/getting-started.mdx
docs/pages/docs/upgrading-to-v3.mdx
docs/pages/docs/wallets.mdx
pnpm-lock.yaml

- Add @cartridge/controller v0.6.0 dependency
- Fix constants import from starknet package (https://www.starknet-react.com/docs/getting-started)
- Improve Cartridge Controller configuration and Session Policies documentation (https://www.starknet-react.com/docs/wallets)
- Fix contract.populate example in upgrading guide (https://www.starknet-react.com/docs/upgrading-to-v3)

docs: update Cartridge dependencies and documentation

---

change/@starknet-react-chains-bbe38f2e-837d-4689-8722-7faf66c01612.json
change/@starknet-react-core-db33869a-82ea-44bf-83c5-6b41899b345c.json
change/create-starknet-fe18f152-b8ae-4289-a412-54aec5477e7a.json
packages/chains/package.json
packages/core/package.json
packages/create-starknet/package.json

- **fix release**
- **Change files**

Correctly publishe v4
