apibara/starknet-react

examples/starknet-react-next/src/pages/index.tsx

I couldn't easily tell if the Value was being incremented after I clicked the increment button. It was difficult for me to compare the hexadecimal values displayed in the **Value:** field. Therefore, this change displays the counter's count in decimal representation.

feat: display count on Next example

---

.changeset/cool-ravens-visit.md
examples/starknet-react-next/src/components/ConnectWallet.tsx
packages/core/src/connectors/base.ts
packages/core/src/connectors/injected.ts
packages/core/src/errors.ts
packages/core/src/providers/starknet/manager.ts
packages/core/src/providers/starknet/model.ts
packages/core/test/providers/block.test.tsx

Fixes https://github.com/apibara/starknet-react/issues/79

feat: disconnect

---

.changeset/red-ads-wait.md
examples/starknet-react-next/src/pages/rerender.tsx
packages/core/src/providers/block/provider.tsx

Reduce the number of rerenders by avoiding updating the current block if it did not change.

Reduce number of rerenders

---

.changeset/wet-cougars-judge.md
examples/starknet-react-next/src/components/IncrementCounter.tsx
examples/starknet-react-next/src/components/TransactionList.tsx
examples/starknet-react-next/src/pages/token.tsx
packages/core/src/hooks/invoke.ts
packages/core/src/providers/transaction/model.ts
packages/core/src/providers/transaction/reducer.ts

Fix #70. I decided to use a more generic `metadata` field to allow application developers store any type of data that makes sense for their application.

Add transaction metadata

---

packages/core/src/connectors/base.ts
packages/core/src/connectors/injected.ts
website/docs/demo.mdx
website/docs/intro.md
website/src/components/Demo/index.tsx

1. generalize wallet refs in docs
2. injected connector `name` and `id` must be dynamic since connector could return diff wallets
3. fixing intro docs
4. fixing demo app

fix: wrong npm libs and misleading id/name

---

packages/core/src/providers/transaction/provider.tsx
packages/core/src/providers/transaction/reducer.ts

This fixes the issue where the transactions would be stuck due to type incompatibility with newest 0.9.0 changes

Fix transaction state tracking

---

.changeset/pink-worms-flow.md
packages/core/src/hooks/call.ts
website/docs/hooks/call.md

By default, starknet.js queries `pending` state of the blockchain (see https://docs.starknet.io/docs/Blocks/transaction-life-cycle/#the-pending-block).
It can be useful to query the `latest` state of the blockchain or even pass a block number, which the starknet.js lib supports.

Add the ability to pass blockNumber to contract call method

---

.changeset/smart-spies-sell.md
packages/core/package.json

When using with a js library, it will try to look for sources in the `src` folder which, at the moment, is not packaged.

Include src folder in package

---

package.json
packages/core/test/devnet.ts
pnpm-lock.yaml

Closes https://github.com/apibara/starknet-react/issues/203
We need to do some changes to support newer `starknet.js` versions. Tests are currently failing, see there https://github.com/apibara/starknet-react/actions/runs/3742966615/jobs/6354784526.
This PR doesn't fix the linked issue but only fixes this commit https://github.com/0xs34n/starknet.js/commit/bb2a8cddc0ca272a3a291668e80c59ff8758e903. If there are plans to support `starknet.js` versions above `v4.15.0` soon then maybe we can keep the issue open

fix: support starknet.js `v4.15.0`

---

packages/core/src/hooks/account.test.tsx
packages/core/src/hooks/account.ts
packages/core/src/hooks/block.test.tsx
packages/core/src/hooks/block.ts
packages/core/src/hooks/call.test.tsx
packages/core/src/hooks/call.ts
packages/core/src/hooks/execute.test.tsx
packages/core/src/hooks/execute.ts
packages/core/src/hooks/receipt.test.tsx
packages/core/src/hooks/receipt.ts
packages/core/src/hooks/transaction.test.tsx
packages/core/src/hooks/transaction.ts

Refactoring to match wagmi's api : #105 
- Add `useBlockNumber` and refactor `useBlock`
- Refactor `useStarknetCall` to `useContractRead`
- Refactor `useTransaction` and `useTransactions`
- Refactor `useTransactionReceipt` to `useWaitForTransaction`
- Refactor `useAccount`
- Refactor `useStarknetExecute` to `useContractWrite`
Already matching wagmi's api : 
- `useNetwork`

Feat: match wagmi api in block, call, receipt and contract

---

packages/core/src/providers/starknet.tsx

When passing `autoConnect = true` to the `StarknetConfig` component, the starknet manager does not handle account change

fix: fix handle account change with autoConnect

---

website/components/CodeBlock/index.tsx

https://user-images.githubusercontent.com/37301269/223188252-bccaa33f-e72d-4df5-9413-829fd181bdf8.mov
https://user-images.githubusercontent.com/37301269/223188412-e58489aa-7951-4943-9947-1d77db018ddd.mov

fix: overflow on Markdown component

---

.changeset/curvy-games-sneeze.md
packages/create-starknet/README.md
packages/create-starknet/helpers/packageManager.ts
packages/create-starknet/index.ts

- Identified which package manager is used thanks to the npm user agent.
- Added option to select the package manager with non-interactive mode
- Updated `README.md`
This change will be used when installing automatically packages when initializing a project (in a next PR)
The next PR will update the documentation website

feat(create-starknet): identify which package mangager is used and add option to select it manually

---

.changeset/beige-pans-run.md
packages/core/src/providers/starknet.tsx

This commit fixes the `handleAccountChanged` function. Previously, when changing accounts in the wallet, starknet-react would not prompt the wallet to approve connecting to the dApp with the new account.
As a side effect, we now detect and handle network changes. 🎉 
Notes:
- `handleAccountChanged` now simply calls the disconnect and connect functions. `connector.initEventListener(handleAccountChanged)` needed to be called after setting `state.connector`. This is why it is now called in a useEffect.
- In the `disconnect` function, some logic has been moved to execute before `state.connector.disconnect()`. This allows for the correct handling of cases where the user changes accounts but rejects approval to connect to the dApp with the new account.

chore: fix change account

---

.changeset/polite-melons-knock.md
package.json
packages/core/package.json
packages/core/src/hooks/block.test.tsx
packages/core/src/hooks/block.ts
packages/core/src/hooks/call.test.tsx
packages/core/src/hooks/execute.test.tsx
packages/core/src/hooks/invoke.test.tsx
packages/core/src/hooks/receipt.test.tsx
packages/core/src/hooks/starknetid.test.tsx
packages/core/src/hooks/starknetid.ts
packages/core/src/hooks/transaction.test.tsx
packages/core/src/providers/starknet.tsx
packages/core/test/devnet.ts
pnpm-lock.yaml

- Updates starknet.js package to latest version 4.22.0 which moves starknet.id functions to Provider instead of Account
- Update starknetid hook to reflect these changes. 
- Adds a custom default provider in provider `starknet`, as starknet.js `defaultProvider` is initialized to testnet2 instead of testnet. 
- Update starknet.id naming contract address on testnet

Update starknetid hook with latest version of starknet.js

---

.changeset/fast-maps-peel.md
packages/core/src/connectors/index.ts
packages/core/src/hooks/balance.test.tsx
packages/core/src/hooks/balance.ts
packages/core/src/hooks/index.ts

Closes #236 
Add a `useBalance` hook, based on the wagmi equivalent, that fetches balance info for ERC 20 tokens.
```ts
const { data } = useBalance({
address, // address to fetch balance for
token, // token address, defaults to ETH token
formatUnits // defaults to token decimals
})
```
Returns the original balance, formatted balance, symbol, and decimals:
```ts
Balance: {data.formatted} {data.symbol}
```

Feat: Add a useBalance hook for ERC20s

---

packages/core/src/hooks/call.ts
packages/core/src/hooks/sign.ts

Why:
- Currently the code example for `useSignTypedData` is incorrect, so on the docs site it doesn't work.
How: 
- Add StarkNetDomain types to the signed object
- Use the hook after the message const is initialized
- Add info about EIP712

Fix useSignTypedData docs

---

packages/core/src/connectors/base.ts
packages/core/src/connectors/injected.ts

Wallet icons can now be accessed with `connector.icon()`. Very useful for dapps to show which wallet is connected

feat: add connector icon support

---

.changeset/two-elephants-wonder.md
packages/core/src/hooks/transaction.ts

We use react-query `invalidateQueries` to invalidate queries on new blocks. 
Since this can result in a lot of RPC calls, we hide it behind a `watch` flag.
Fix #247

Invalidate transaction queries on new block

---

.changeset/strong-dolls-obey.md
packages/core/src/connectors/base.ts
packages/core/src/connectors/index.ts
packages/core/src/connectors/injected.ts

Sometimes we would get different values based on the type of wallet
connected (Argent X or Braavos).
By specifying that we want v4, we will always receive the correct value.

fix: request AccountInterface v4 to injected wallets

---

.changeset/cuddly-berries-listen.md
.github/PULL_REQUEST_TEMPLATE/default.md
packages/core/src/hooks/network.ts

This PR fixes #283
Replaced the use of `useQuery` with `useEffect` and `useState` to refresh the
value of the chain id when the provider changes.
- Run `pnpm dev:web` to start the documentation
- Opened the `useNetwork` hook page
- Connected Argent X, changed network and verified the network name changes
* This one is not working, but it's a bug in Argent.
- Connected Braavos, changed network and verified the network name changes

fix: handle network changes in useNetwork hook

---

.changeset/tiny-apes-give.md
.changeset/tough-timers-rescue.md
packages/core/src/connectors/discovery.ts
packages/core/src/connectors/helpers.ts
packages/core/src/connectors/index.ts
packages/core/src/connectors/injected.ts
packages/core/src/hooks/useAccount.ts
website/app/hooks/[[...slug]]/page.tsx
website/app/hooks/layout.tsx
website/components/starknet/connect-modal.tsx
website/components/starknet/provider.tsx
website/content/docs/getting-started.mdx
website/content/docs/wallets.mdx
website/content/hooks/useInjectedConnectors.mdx
website/contentlayer.config.ts
website/lib/sidebar.ts
website/styles/globals.css

This PR fixes some of the remaining bugs in the connector handling code.

Improve account connection

---

README.md
packages/chains/src/types.ts
packages/core/src/context/index.tsx
packages/core/src/context/starknet.tsx
packages/core/src/providers/alchemy.ts
packages/core/src/providers/factory.ts
packages/core/src/providers/infura.ts
packages/core/src/providers/jsonrpc.test.ts
packages/core/src/providers/jsonrpc.ts
packages/core/src/providers/lava.ts
packages/core/src/providers/public.test.ts
packages/core/src/providers/public.ts
packages/core/test/react.tsx
website/components/starknet/provider.tsx
website/content/docs/getting-started.mdx
website/content/docs/providers.mdx
website/content/docs/upgrading.mdx
website/content/hooks/useInjectedConnectors.mdx

adds functionality to pass headers as arguments to jsonRpcProvider. this is useful as some rpcs require passing the auth token in a header

Custom headers for jsonRpcProvider

---

.changeset/violet-lizards-give.md
packages/core/src/hooks/index.ts
packages/core/src/hooks/useStarkProfile.ts
website/components/demos/starknetid.tsx
website/content/demos/starknetid.mdx
website/content/hooks/query/useStarkProfile.mdx

This PR introduce a new hook `useStarkProfile` which retrieves a user starkname and all data he may have written on his starknet id :  his profile picture metadata, his social media verification (twitter id, github id, discord id), and if the user has done his proof of personhood verification.

feat: add useStarkProfile hook

---

website/components/demos/contract-read.tsx

Due to the serialization of bigint. 
https://deploy-preview-417--starknet-react.netlify.app/demos/contract-read
Closes #416

Fix Unhandled Runtime Error on contract read page

---

.changeset/six-crews-jog.md
packages/core/src/hooks/index.ts
packages/core/src/hooks/useEstimateFees.ts
website/content/hooks/query/useEstimateFees.mdx

As described in the issue #411, dapps sometimes needs fees estimation before doing the actual contract call. For this, I've created the useEstimateFees hook.
- Added useEstimateFees custom hook.
- Added relevant documentation in the docs with usage example.

Feat: useEstimateFees hook

---

.changeset/rich-elephants-marry.md
packages/core/src/hooks/useBalance.ts
website/components/demos/balance.tsx

Now that the chain produces less blocks, it helps to request the balance for pending blocks.
Add option to specify the `blockIdentifier`.

core: add option to override blockIdentifier in useBalance

---

.changeset/stale-numbers-juggle.md
packages/core/src/hooks/useStarkProfile.ts

This PR fixes a bug in `useStarkProfile` which currently returns an error for Blobbert NFTs that are set as profile picture.

fix: useStarkProfile to work with base64 tokenURI

---

.changeset/hot-buses-bow.md
packages/core/src/hooks/useStarkAddress.ts
packages/core/src/hooks/useStarkName.ts
packages/core/src/hooks/useStarkProfile.ts

We will soon update the starknet ID naming contract function `address_to_domain`, adding an additional `hint` parameter that will allow us to support CCIP reverse resolving of domains. This change will break `useStarkName` & `useStarkProfile` hooks. In prevision of this, to avoid any errors for people using these hooks, I updated them so that they will first try to make the query with the new `hint` parameter, and if it fails try without.
I also took this opportunity to fix #419

ref: update starknetid hooks for address_to_domain update

---

packages/core/src/connectors/injected.ts

Update `InjectedConnector` class to work with starknet.js V6:
- fix: `chainId` method
- fix: `connect` method
- fix: `account` method 
/!\ temporary solution due to `StarknetWindowObject` not being correctly typed. Most of the properties are missing yet those properties does exist in the window object meaning they are here but typescript prevent us from accessing it.
In order to have this properly made we need to wait for `starknet-types` to be updated with a stable version.
/!\ On top of that `StarknetWindowObject` does have the property account filled only when we do the whole process of connection with a wallet, otherwise it's not persisted, most possibly due to the library itself being unstable.

feat: wallet connection using starknet v6

---

.changeset/shy-planets-poke.md
packages/core/src/context/starknet.tsx

The current implementation of the query client within the function component leads to the creation of a new query client on each re-render. Consequently, this behavior results in the loss of data and caches associated with the query client.
This PR addresses the issue by relocating the default query client outside of the function component. By doing so, we ensure that the query client persists across re-renders, maintaining data integrity and cache consistency.
While it's possible to resolve this issue by directly providing the query client to the Provider on usage, this caused us some time to locate and fix the issue, hence the decision to refactor the implementation.

fix: move the default query client to outside of the component

---

packages/chains/package.json
packages/chains/tsconfig.json
packages/core/package.json
packages/core/src/context/starknet.tsx
packages/core/src/hooks/useAccount.ts
packages/core/src/hooks/useBalance.ts
packages/core/src/hooks/useBlock.ts
packages/core/src/hooks/useBlockNumber.ts
packages/core/src/hooks/useCall.ts
packages/core/src/hooks/useConnect.ts
packages/core/src/hooks/useContract.ts
packages/core/src/hooks/useDeployAccount.ts
packages/core/src/hooks/useDisconnect.ts
packages/core/src/hooks/useEstimateFees.ts
packages/core/src/hooks/useExplorer.ts
packages/core/src/hooks/useInvalidateOnBlock.ts
packages/core/src/hooks/useNetwork.ts
packages/core/src/hooks/useProvider.ts
packages/core/src/hooks/useReadContract.ts
packages/core/src/hooks/useStarkAddress.ts
packages/core/src/hooks/useStarkName.ts
packages/core/src/hooks/useStarkProfile.ts
packages/core/src/hooks/useTransactionReceipt.ts
packages/core/src/hooks/useWalletRequest.ts
packages/core/src/providers/jsonrpc.ts
packages/core/tsconfig.json

At the moment, any change to a package (core, chains, etc) requires compiling
the project before it can be used in the documentation.
This PR changes the default configuration used by pnpm/npm to provide Typescript
files and exports the compiled javascript files only on publish.

Live typescript

---

docs/components/demo/declare-contract.tsx
docs/components/demo/index.ts
docs/components/demo/sign-typed-data.tsx
docs/pages/demo/declare-contract.mdx
docs/pages/demo/sign-typed-data.mdx
docs/pages/index.mdx
packages/core/src/connectors/mock.ts
packages/core/src/hooks/useAddChain.test.ts
packages/core/src/hooks/useDeclareContract.test.ts
packages/core/src/hooks/useEstimateFees.test.ts
packages/core/src/hooks/useSendTransaction.test.ts
packages/core/src/hooks/useSign.test.ts
packages/core/src/hooks/useSwitchChain.test.ts
packages/core/src/hooks/useWalletRequest.test.ts
packages/core/test/react.tsx

- refactored `MockConnector` and added more `request` methods
- updated `customRenderHook` and `customRender` to accept `connectorOptions` for `MockConnector`
- demo for `useDeclareContract` & `useSignTypedData`
- added tests for `useAddChain`, `useSwitchChain`, `useDeclareContract`, `useSendTransaction`, `useEstimateFees`, `useWalletRequest` & `useSignTypedData`

feat: mock connector and tests 

---

.changeset/real-ducks-dress.md
packages/core/src/hooks/useBalance.test.ts
packages/core/src/hooks/useBalance.ts
packages/core/src/hooks/useContractRead.ts
packages/core/src/hooks/useEstimateFees.ts
packages/core/src/hooks/useStarkName.ts
packages/core/src/hooks/useStarkProfile.ts
website/components/demos/contract-read.tsx

The query hooks have an `enabled` flag that should be forwarded to `react-query`.
This was not the case for some hooks.
This PR forwards the `enabled` flag to `react-query` for all hooks.
We updated the `read-contract` demo to have an option to enable/disable the query.

core: fix enable/disable query

---

biome.json
docs/components/demo/index.ts
docs/components/demo/nonce-for-address.tsx
docs/pages/demo/index.mdx
docs/pages/demo/nonce-for-address.mdx
docs/pages/docs/hooks/use-nonce-for-address.mdx
docs/sidebar.ts
packages/core/src/hooks/index.ts
packages/core/src/hooks/use-nonce-for-address.test.ts
packages/core/src/hooks/use-nonce-for-address.ts

- Add a new `useNonceForAddress` hook which fetches the nonce associated with the given address in the given block
- Resolves #470

core: add useNonceForAddress hook

---

docs/package.json
pnpm-lock.yaml

Solves #483 
- Starknetkit was updated to its latests version `2.2.25` using `pnpm add starknetkit@next`.
- The app commands were tested to make this wasn't a breaking change (`build`, `preview`, `dev`, ...)
- The [release docs](https://github.com/argentlabs/starknetkit/releases) as well as the specific [code](https://github.com/argentlabs/starknetkit/commit/071acfb1c62ccc241f5723835db387ff2ab64488) were checked to make sure there was no breaking change or code needed to be change on the demo project.
- A complete test was performed while running the demo locally. Both argent and braavos wallet's connection was tested.

Upgrade skartnetkit to latest version

---

packages/core/src/hooks/use-account.test.ts
packages/core/src/hooks/use-account.ts
packages/core/src/hooks/use-block.test.ts
packages/core/src/index.ts
packages/core/src/query.ts
packages/core/src/utils.ts
packages/core/test/devnet.ts
pnpm-lock.yaml

Closes #452 
To address the issue with address formatting in the `useAccount` hook, I have implemented a new `getAddress` function. This function ensures that addresses are consistently prefixed with 0x, aligning with the expected Address type.

fix: [Type] useAccount.address should return an Address type

---

packages/core/src/hooks/use-account.ts

resolves #482
- removed `for` loop and added `Promise.any` for parallel polling of wallets.
- `Promise.any` will make sure to connect to the first wallet which meets the required conditions and then stop looking for wallets.
- This would essentially reject the promises where conditions are not meeting, resolve the first promise where conditions are met and proceed ahead, ignoring other unresolved promises.

Parallel Wallet Polling in useAccount hook

---

change/@starknet-react-core-62cd0e5a-40e2-4894-8619-9b25fa4b57b1.json
change/@starknet-react-kakarot-4afaa398-6b8f-442a-90fb-3d80b5cb73d1.json
change/create-starknet-f3996a65-d78b-4381-b65f-3e3cfdba2c30.json
docs/components/demo/starknetkit.tsx
docs/components/starknet/provider.tsx
docs/package.json
packages/core/src/connectors/base.ts
packages/core/src/connectors/index.ts
packages/core/src/connectors/injected.ts
packages/core/src/context/starknet.tsx
packages/create-starknet/src/templates/next/src/components/starknet-provider.tsx
packages/kakarot/CHANGELOG.md
packages/kakarot/README.md
packages/kakarot/package.json
packages/kakarot/src/chains.ts
packages/kakarot/src/connectors.ts
packages/kakarot/src/index.ts
packages/kakarot/src/kakarot.ts
packages/kakarot/tsconfig.json
packages/kakarot/tsup.config.ts
pnpm-lock.yaml
pnpm-workspace.yaml

Initial work on implementing a wrapper around EVM connectors through Kakarot

feat:kakarot connectors

---

change/@starknet-react-core-bd9008d8-3ad5-49ff-a337-7953d7919b14.json
docs/components/demo/account.tsx
packages/chains/package.json
packages/core/package.json
packages/core/src/connectors/injected.ts
packages/core/src/context/starknet.tsx
packages/core/src/hooks/use-account.ts
packages/create-starknet/package.json
packages/kakarot/package.json
pnpm-lock.yaml

In some cases, calls to the wallet API can take a long time (>100ms) so the
library should make as few of them as possible to minimize the time it takes to
connect to a wallet.
- Reduce the calls to `wallet_requestAccounts` used to check if the wallet is locked.
- Update the `address` property in the `useAccount` hook without waiting for the `account` object to be fully built.
Use the `account` demo to test that less calls are made to the wallet. You can
set a breakpoint in the `InjectedConnector.request` function.

core: reduce the number of wallet api calls

---

change/@starknet-react-core-e33b670a-0093-445e-8cbc-d0a9c19083cd.json
packages/core/src/context/starknet.tsx

when user disconnects dApp from the wallet ui itself, it will emit `disconnect` event using which we update starknet state.
resolves #520

core: add disconnect event listener for wallets

---

change/@starknet-react-kakarot-fa74fe3e-4f70-4564-b900-7956eec1f374.json
packages/kakarot/package.json
packages/kakarot/src/index.ts
packages/kakarot/src/kakarot.ts

- Fixes the address of the kakarot multicall precompile
- Unsupported wallet_* methods now throw an error instead of returning false

fix: kakarot connector

---

docs/pages/demo/account.mdx
docs/pages/demo/add-chain.mdx
docs/pages/demo/balance.mdx
docs/pages/demo/change-default-network.mdx
docs/pages/demo/declare-contract.mdx
docs/pages/demo/estimate-fees.mdx
docs/pages/demo/nonce-for-address.mdx
docs/pages/demo/read-contract.mdx
docs/pages/demo/send-transaction.mdx
docs/pages/demo/sign-typed-data.mdx
docs/pages/demo/stark-address.mdx
docs/pages/demo/stark-name.mdx
docs/pages/demo/stark-profile.mdx
docs/pages/demo/starknetkit.mdx
docs/pages/demo/switch-chain.mdx
docs/pages/demo/wallet-permission.mdx

closes #518 
The changes include the following
- Adds a description of the demo page
- Adds a link to github containing the source code snippet.

Add code snippet to demo pages

---

change/@starknet-react-kakarot-35774e84-0f76-4f61-996a-76eba0d19258.json
packages/kakarot/src/kakarot.ts

- Fixes the encoding of multicalls (removes unwanted `0x` hex prefixes)
- Closes https://github.com/apibara/starknet-react/issues/530 by changing the return type for kakarot's wallet_InvokeTransaction route

fix: kakarot invoke returndata and multicall encoding

---

change/@starknet-react-core-683ce251-dd83-4e84-a241-b4e6117f44af.json
docs/components/starknet/provider.tsx
packages/core/src/connectors/discovery.ts
packages/core/src/connectors/helpers.ts
packages/core/src/connectors/index.ts
packages/core/src/connectors/legacy.ts

This PR adds a new `LegacyInjectedConnector` to allow using (some) methods from wallets that haven't upgraded to the new wallet api.

core: add legacy connector adapter

---

change/@starknet-react-core-a41ab949-7f4b-43ab-9196-a874280859b9.json
packages/core/src/hooks/use-call.ts

Resolves https://github.com/apibara/starknet-react/issues/548

feat: useCall convert bigint in args to string

---

change/@starknet-react-core-6b51603b-833a-4afc-a653-2260fa46ed82.json
docs/components/demo/events.tsx
docs/components/demo/index.ts
docs/pages/demo/events.mdx
docs/pages/demo/index.mdx
docs/pages/docs/hooks/use-events.mdx
docs/sidebar.ts
packages/core/src/hooks/index.ts
packages/core/src/hooks/use-events.test.ts
packages/core/src/hooks/use-events.ts
packages/core/src/query.ts

In this PR, an implementation for a new hook `useEvents` that supports fetching Starknet events continuously, a demo is available to show how to use it
https://github.com/user-attachments/assets/4748c568-e816-42fe-bed4-b8f3b33bdb0f
Closes #465

Implement `useEvents` hook

---

change/@starknet-react-core-b3c27a78-1dce-463e-aba8-3639dc04e904.json
packages/core/src/providers/index.ts

This adds re-exports for cartridge and slot, these are not available in latest versions.

fix: re exports packages

---

docs/package.json
docs/pages/docs/getting-started.mdx

- Update ControllerConnector configuration example to align with @cartridge/connector v0.6.0 API
- Add proper chains configuration with Sepolia and Mainnet RPC URLs
- Add defaultChainId parameter using StarknetChainId.SN_SEPOLIA
- Import required constants from starknet and @starknet-react/core packages
The current getting-started guide uses an outdated configuration that's incompatible with the latest @cartridge/connector v0.6.0. This PR updates the example code to prevent TypeScript errors and ensure proper functionality with the current version.
- Verified the updated configuration works with @cartridge/connector v0.6.0
- Confirmed all TypeScript errors are resolved
- Tested connectivity with both Sepolia and Mainnet networks

docs: update Cartridge Controller configuration in getting-started guide

---

change/@starknet-react-core-55fc48f8-fbc6-461f-b588-5ec9b69b3da0.json
packages/core/src/hooks/use-account.ts

When user connects their wallet and then a component using `useAccount` hook is mounted, the address is `undefined` and then updated to user's address immediately.
This lead to showing of loading state for a split second, which makes the app "flicker".
If user address is set on the Provider, the initial state of `useAccount` is `connected` with user address.

core: useAccount address on initial render

---

docs/pages/docs/getting-started.mdx

This PR corrects a typo in the documentation where "Tankstack Query" was mistakenly written instead of "Tanstack Query." This fix ensures the correct naming of the Tanstack Query library and improves clarity in the documentation.

Updates Tankstack Query to Tanstack Query

---

README.md
change/@starknet-react-core-d76d2b5e-d4f0-4eba-9467-ffffd0bf6634.json
change/create-starknet-c268a259-98a7-4caf-b583-8bd7118fe629.json
docs/components/starknet/bar.tsx
docs/components/starknet/provider.tsx
docs/pages/docs/getting-started.mdx
docs/pages/docs/hooks/use-injected-connectors.mdx
docs/pages/docs/wallets.mdx
packages/core/src/connectors/discovery.ts
packages/core/src/connectors/helpers.ts
packages/core/src/connectors/index.ts
packages/create-starknet/src/templates/next/src/components/starknet-provider.tsx
packages/create-starknet/src/templates/vite/src/main.tsx

Argent rebranded to Ready. This PR updates the name.
We also update the discovery mechanism to use the wallet name hardcoded in the library to avoid content flashing once the injected wallet is discovered.

Rename Argent to Ready

---

docs/pages/docs/paymaster-providers.mdx

A follow-up to #569
Noting that unliked other Paymaster integrations, the Controller requires no additional code-level configuration and can be managed entirely through the [Slot CLI](https://docs.cartridge.gg/slot/paymaster).

feat(docs): add Cartridge Controller paymaster information

---

change/@starknet-react-core-b60b3cf8-5748-4f78-a2d2-9b2232228eac.json
packages/core/src/connectors/injected.ts

Fixes broken wallet connection from the previous release and resolves an issue where, if the dApp connects to `sepolia` while the wallet is on `mainnet`, the wallet correctly switches to `sepolia`, but the accounts request is made before the switch. As a result, a `mainnet` account was returned instead of a `sepolia` one.
This behavior was supposed to be handled by the `accountsChanged` event, but in the existing code the event handlers were registered *after* requesting accounts, so the event never fired. Now, the event handlers are registered *before* requesting accounts and switching chains which resolves this bug.

core: fix wallet connection and wrong account on network switch
